openapi: 3.0.1
info:
  title: Operator API
  version: 1.0.0
servers:
  - url: http://localhost
    description: My server

paths:
  /operator:
    post:
      summary: Add a new operator
      operationId: AddOperator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Operator"
      responses:
        "200":
          description: Operator added successfully
        "400":
          description: Invalid input
  /operator/{id}:
    get:
      summary: Get operator by ID
      operationId: GetOperator
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Operator found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Operator"
  /client/{companyName}:
    get:
      summary: Get client by companyName
      operationId: checkClient
      parameters:
        - name: companyName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Client found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
components:
  schemas:
    Operator:
      type: object
      properties:
        id:
          type: integer
        operatorId:
          type: integer
        surname:
          type: string
        name:
          type: string
      required:
        - id
        - name
        - surname
        - userId
    Client:
      type: object
      properties:
        id:
          type: integer
        clientId:
          type: integer
        companyName:
          type: string
      required:
        - id
        - clientId
        - companyName
